// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xXEtVZyFmTrU3lnESu5j1p2OE8gjBUM',
    appId: '1:2795089756:web:12ad99f5addbd628cddb99',
    messagingSenderId: '2795089756',
    projectId: 'sefernur-app',
    authDomain: 'sefernur-app.firebaseapp.com',
    storageBucket: 'sefernur-app.firebasestorage.app',
    measurementId: 'G-H9XYGKZE0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaYh21tWvrjjaoTCt-gWfZ1x7cBynwezc',
    appId: '1:2795089756:android:ccb69b166c28a607cddb99',
    messagingSenderId: '2795089756',
    projectId: 'sefernur-app',
    storageBucket: 'sefernur-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3FxWyEFAlNeYW1FTZ-Y8V7-RfzEdycM',
    appId: '1:2795089756:ios:62ae1b309c3f43c1cddb99',
    messagingSenderId: '2795089756',
    projectId: 'sefernur-app',
    storageBucket: 'sefernur-app.firebasestorage.app',
    iosBundleId: 'com.eyexapp.sefernur',
  );

}